# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-25 09:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hood', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('content', tinymce.models.HTMLField(blank=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UpdateHood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['user']},
        ),
        migrations.RenameField(
            model_name='business',
            old_name='occupant',
            new_name='business_owner',
        ),
        migrations.RenameField(
            model_name='hood',
            old_name='occupant',
            new_name='member',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='occupant',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='business',
            name='hood',
        ),
        migrations.RemoveField(
            model_name='hood',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='hood',
            name='location',
        ),
        migrations.AddField(
            model_name='business',
            name='business_hood',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business', to='hood.Hood'),
        ),
        migrations.AddField(
            model_name='business',
            name='description',
            field=tinymce.models.HTMLField(blank=True),
        ),
        migrations.AddField(
            model_name='business',
            name='email',
            field=models.EmailField(blank=True, max_length=70),
        ),
        migrations.AddField(
            model_name='hood',
            name='member_count',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='hood',
            name='health_details',
            field=tinymce.models.HTMLField(blank=True),
        ),
        migrations.AlterField(
            model_name='hood',
            name='name',
            field=models.CharField(blank=True, default='e.g Karen, Kikuyu, Ngong, Limuru etc', max_length=50),
        ),
        migrations.AlterField(
            model_name='hood',
            name='police_details',
            field=tinymce.models.HTMLField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(blank=True, max_length=100),
        ),
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.DeleteModel(
            name='Health',
        ),
        migrations.DeleteModel(
            name='locations',
        ),
        migrations.DeleteModel(
            name='Police',
        ),
        migrations.AddField(
            model_name='updatehood',
            name='hood_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hood.Hood'),
        ),
        migrations.AddField(
            model_name='updatehood',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='post_hood',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hood.Hood'),
        ),
    ]
