# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-25 23:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hood', '0002_auto_20190325_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='hood',
            name='user_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hoods', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='hood',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
