# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-25 23:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0003_auto_20190326_0205'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UpdateHood',
            new_name='Join',
        ),
    ]
