# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-26 00:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0004_auto_20190326_0245'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='phone_number',
            field=models.TextField(blank=True, max_length=70),
        ),
    ]
