# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-26 00:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0005_business_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='phone_number',
            new_name='phone',
        ),
    ]
